### ISSUE TITLE
Thies variables to be removed from NetCDFs

### ISSUE THREAD

**Issue by andrecastro0o** [ruisdael-observatory/disdroDL#18]
Original comment from @mschleiss https://github.com/ruisdael-observatory/disdroDL/issues/2#issuecomment-2293467087

>  
        The variables to remove are:
        - weather_code_synop_4677_5min(time)
        - weather_code_synop_4680_5min(time)
        - weather_code_metar_4678_5min\ \(unitless\)(time)
        - all_precip_intensity_5min(time)
        - accumulated_precip_amount(time)
        - static_signal(time)
        - status_laser_temperature_analogue(time)
        - status_laser_temperature_digital(time)
        - status_laser_current_analogue(time)
        - status_laser_current_digital(time)
        - status_sensor_supply(time)
        - status_heating_laser_head(time)
        - status_heating_receiver(time)
        - status_temperature_sensor(time)
        - status_heating_supply(time)
        - status_heating_housing(time)
        - status_heating_heads(time)
        - status_heating_carriers(time) 
        

Merge to branch [https://github.com/ruisdael-observatory/disdroDL/tree/0.3.2](https://github.com/ruisdael-observatory/disdroDL/tree/0.3.2)

**Comment by andrecastro0o** [comment]
use key/value: `include_in_nc: 'never'`  to stop the vars from being included in the NetCDF

Example:
```yaml
    '5':
        dimensions:
            - time
        dtype: 'S4'
        include_in_nc: 'never'
        var_attrs:
            long_name: 'Date of the sensor [1]'
            standard_name: 'sensor_date'
            units: '1'
```
