### ISSUE TITLE
bring back citation.cff file

### ISSUE THREAD

**Issue by andrecastro0o** [ruisdael-observatory/disdroDL#39]
I cannot find the documentation on this at the moment, but I believe this is how zenodo gets the metadata on a repository

```
# This CITATION.cff file was generated with cffinit.
# Visit https://bit.ly/cffinit to generate yours today!

cff-version: 1.2.0
title: 'disdroDL: Disdrometer data logging software'
message: >-
  If you use this software, please cite it using the
  metadata from this file.
type: software
authors:
  - given-names: André
    family-names: Castro
    orcid: 'https://orcid.org/0000-0002-7839-3698'
  - orcid: 'https://orcid.org/0000-0002-4667-5500'
    given-names: Marc
    family-names: Schleiss
identifiers:
  - type: doi
    value: 10.5281/zenodo.12800589
    description: v0.3.1 DOI
repository-code: 'https://github.com/ruisdael-observatory/disdroDL/'
abstract: ' disdrometer data logger to NetCDF '
keywords:
  - NetCDF
  - Disdrometer
  - Atmospheric Sciences
  - Precipitation
  - Python
  - Ruisdael Observatory
license: GPL-3.0
commit: 97aaa245a3a38ac560cc4ed3bbe35d67ee2ba1b7
version: 0.3.1
date-released: '2024-07-23'
```
